ERROR:root:too many values to unpack (expected 2)
DEBUG:django.db.backends:(0.000) SELECT "pacifico_aseguradora"."id", "pacifico_aseguradora"."descripcion", "pacifico_aseguradora"."codigo" FROM "pacifico_aseguradora"; args=(); alias=default
DEBUG:django.template:Exception while resolving variable 'lineaAuto' in template 'fideicomiso_form.html'.
Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 883, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
KeyError: 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 899, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 906, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [lineaAuto] in {'auxMonto2': Decimal('22101.13'), 'numero_cotizacion': 45, 'r1': Decimal('15.00'), 'tasaEstimada': Decimal('11.69'), 'calcComiCierreFinal': Decimal('14.34'), 'auxPlazoPago': 96, 'wrkLetraSinSeguros': Decimal('369.58'), 'wrkLetraSeguro': Decimal('17.40'), 'wrkMontoLetra': Decimal('386.98'), 'montoMensualSeguro': Decimal('43.36'), 'wrkLetraConSeguros': Decimal('430.34'), 'tablaTotalPagos': Decimal('37150.08'), 'nombreCliente': 'EDUARDO REYES', 'valorAuto': Decimal('23500.00'), 'abono': Decimal('4700.00'), 'salarioBaseMensual': Decimal('0.00'), 'totalDescuentosLegales': Decimal('0.00'), 'totalDescuentoDirecto': Decimal('0.00'), 'totalPagoVoluntario': Decimal('0.00'), 'salarioNetoActual': Decimal('0.00'), 'salarioNeto': Decimal('-430.34'), 'porSalarioNeto': Decimal('0.00'), 'totalIngresosAdicionales': Decimal('0.00'), 'totalIngresosMensualesCompleto': Decimal('0.00'), 'totalDescuentosLegalesCompleto': Decimal('0.00'), 'salarioNetoActualCompleto': Decimal('0.00'), 'salarioNetoCompleto': Decimal('-430.34'), 'porSalarioNetoCompleto': Decimal('0.00'), 'cosalarioBaseMensual': None, 'cototalDescuentosLegales': None, 'cototalDescuentoDirecto': None, 'cototalPagoVoluntario': None, 'cosalarioNetoActual': None, 'cosalarioNeto': None, 'coporSalarioNeto': None, 'cototalIngresosAdicionales': Decimal('0.00'), 'cototalIngresosMensualesCompleto': None, 'cototalDescuentosLegalesCompleto': None, 'cosalarioNetoActualCompleto': None, 'cosalarioNetoCompleto': None, 'coporSalarioNetoCompleto': None, 'porcentajeLetraSeguro': 0, 'coporcentajeLetraSeguro': 0, 'porcentajeLetraSeguroCompleto': 0, 'coporcentajeLetraSeguroCompleto': 0, 'familiarSalarioBaseMensual': 0, 'familiarSalarioNeto': Decimal('-430.34'), 'familiarporNetoActual': 0, 'familiarpoSalarioNeto': 0, 'familiarNetoActualCompleto': 0, 'familiarporNetoActualCompleto': 0, 'familiarSalarioNetoCompleto': Decimal('-430.34'), 'familiarporSalarioNeto': 0}
DEBUG:django.template:Exception while resolving variable 'lineaAuto' in template 'fideicomiso_form.html'.
Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 883, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
KeyError: 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 899, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 906, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [lineaAuto] in {'auxMonto2': Decimal('22101.13'), 'numero_cotizacion': 45, 'r1': Decimal('15.00'), 'tasaEstimada': Decimal('11.69'), 'calcComiCierreFinal': Decimal('14.34'), 'auxPlazoPago': 96, 'wrkLetraSinSeguros': Decimal('369.58'), 'wrkLetraSeguro': Decimal('17.40'), 'wrkMontoLetra': Decimal('386.98'), 'montoMensualSeguro': Decimal('43.36'), 'wrkLetraConSeguros': Decimal('430.34'), 'tablaTotalPagos': Decimal('37150.08'), 'nombreCliente': 'EDUARDO REYES', 'valorAuto': Decimal('23500.00'), 'abono': Decimal('4700.00'), 'salarioBaseMensual': Decimal('0.00'), 'totalDescuentosLegales': Decimal('0.00'), 'totalDescuentoDirecto': Decimal('0.00'), 'totalPagoVoluntario': Decimal('0.00'), 'salarioNetoActual': Decimal('0.00'), 'salarioNeto': Decimal('-430.34'), 'porSalarioNeto': Decimal('0.00'), 'totalIngresosAdicionales': Decimal('0.00'), 'totalIngresosMensualesCompleto': Decimal('0.00'), 'totalDescuentosLegalesCompleto': Decimal('0.00'), 'salarioNetoActualCompleto': Decimal('0.00'), 'salarioNetoCompleto': Decimal('-430.34'), 'porSalarioNetoCompleto': Decimal('0.00'), 'cosalarioBaseMensual': None, 'cototalDescuentosLegales': None, 'cototalDescuentoDirecto': None, 'cototalPagoVoluntario': None, 'cosalarioNetoActual': None, 'cosalarioNeto': None, 'coporSalarioNeto': None, 'cototalIngresosAdicionales': Decimal('0.00'), 'cototalIngresosMensualesCompleto': None, 'cototalDescuentosLegalesCompleto': None, 'cosalarioNetoActualCompleto': None, 'cosalarioNetoCompleto': None, 'coporSalarioNetoCompleto': None, 'porcentajeLetraSeguro': 0, 'coporcentajeLetraSeguro': 0, 'porcentajeLetraSeguroCompleto': 0, 'coporcentajeLetraSeguroCompleto': 0, 'familiarSalarioBaseMensual': 0, 'familiarSalarioNeto': Decimal('-430.34'), 'familiarporNetoActual': 0, 'familiarpoSalarioNeto': 0, 'familiarNetoActualCompleto': 0, 'familiarporNetoActualCompleto': 0, 'familiarSalarioNetoCompleto': Decimal('-430.34'), 'familiarporSalarioNeto': 0}
INFO:django.server:"POST /cotizacion/45/ HTTP/1.1" 200 201038
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/anaconda3/lib/python3.11/_strptime.py first seen with mtime 1681948558.9095042
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/messages/storage/session.py first seen with mtime 1732569332.5019946
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/messages/storage/fallback.py first seen with mtime 1732569332.5018916
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/sessions/serializers.py first seen with mtime 1732569332.5685349
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/conf/locale/en/formats.py first seen with mtime 1732569332.0692546
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/messages/storage/cookie.py first seen with mtime 1732569332.5017526
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/conf/locale/en/__init__.py first seen with mtime 1732569332.0690286
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/messages/context_processors.py first seen with mtime 1732569332.500866
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/context_processors.py first seen with mtime 1732569332.7133355
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/auth/context_processors.py first seen with mtime 1732569332.2745264
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/fideicomiso/fideicomiso.py previous mtime: 1738264416.1095157, current mtime: 1738271479.3495984
DEBUG:django.utils.autoreload:/Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/fideicomiso/fideicomiso.py notified as changed. Signal results: [(<function template_changed at 0x1051b0f40>, None), (<function translation_file_changed at 0x105c6dc60>, None)].
INFO:django.utils.autoreload:/Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/fideicomiso/fideicomiso.py changed, reloading.
